models.py
from exts import db
from datetime import datetime


class UserModel(db.Model):
    __tablename__ = "user"
    id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    username = db.Column(db.String(20), nullable=False)
    password = db.Column(db.String(25), nullable=False)
    email = db.Column(db.String(50), nullable=False, unique=True)


class QuestionModel(db.Model):
    __tablename__ = "question"
    id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    title = db.Column(db.String(100), nullable=False)
    content = db.Column(db.Text, nullable=False)
    create_time = db.Column(db.DateTime, default=datetime.now)

    author_id = db.Column(db.Integer, db.ForeignKey("user.id"))
    author = db.relationship(UserModel, backref="questions")


class ReplyModel(db.Model):
    __tablename__ = "reply"
    id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    content = db.Column(db.Text, nullable=False)
    create_time = db.Column(db.DateTime, default=datetime.now)
    question_id = db.Column(db.Integer, db.ForeignKey("question.id"))
    question = db.relationship(QuestionModel, backref="replies")
    user_id = db.Column(db.Integer, db.ForeignKey("user.id"))
    user = db.relationship(UserModel, backref="replies")


class Post(db.Model):
    __tablename__ = "post"
    id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    title = db.Column(db.String(100), nullable=False)
    content = db.Column(db.Text, nullable=False)

blueprints/forms.py
import wtforms
from wtforms.validators import Email, Length, EqualTo
from models import UserModel


class RegisterForms(wtforms.Form):
    email = wtforms.StringField(validators=[Email(message="Wrong Email")])
    username = wtforms.StringField(validators=[Length(min=3, max=20, message="Wrong Username")])
    password = wtforms.StringField(validators=[Length(min=6, max=25, message="Password Format Error")])
    passwordConfirm = wtforms.StringField(validators=[EqualTo("password")])

    def validate_email(form, field):
        email = field.data
        user = UserModel.query.filter_by(email=email).first()
        if user:
            raise wtforms.ValidationError(message="This Email has been registered")


class LoginForm(wtforms.Form):
    username = wtforms.StringField(validators=[Length(min=3, max=20, message="Wrong Username")])
    password = wtforms.StringField(validators=[Length(min=6, max=25, message="Password Format Error")])


class QuestionForm(wtforms.Form):
    title = wtforms.StringField(validators=[Length(min=3, max=100, message="Title Format Error")])
    content = wtforms.StringField(validators=[Length(min=3, message="Content Format Error")])

forms.py
# forms.py
from wtforms import Form, StringField, SubmitField
from wtforms.validators import DataRequired


class SearchForm(Form):
    query = StringField('Search', validators=[DataRequired()])
    submit = SubmitField('Search')

app.py
from flask import Flask, render_template, session, g, jsonify, request
from flask_migrate import Migrate

from blueprints.auth import bp as auth_bp
from blueprints.qa import bp as qa_bp
from config import Config
from exts import db
from forms import SearchForm
from models import UserModel, Post, QuestionModel, ReplyModel

app = Flask(__name__)
app.config.from_object(Config)

db.init_app(app)

migrate = Migrate(app, db)

app.register_blueprint(qa_bp)
app.register_blueprint(auth_bp)

from exts import db as db1


@app.route("/", methods=["GET", "POST"])
def index():
    form = SearchForm(request.form)
    posts = Post.query.all()
    if form.validate():
        query = form.query.data
        posts = Post.query.filter(
            (Post.title.ilike(f'%{query}%')) |
            (Post.content.ilike(f'%{query}%'))
        ).all()
    return render_template("index.html", form=form, posts=posts)

@app.route('/movieTalk', methods=["GET", "POST"])
def movie_talk():
    if request.method == 'POST':
        data = request.form.to_dict()
        question = QuestionModel(title=data.get('title'), content=data.get('content'), author_id=g.user.id)
        db1.session.add(question)
        db1.session.commit()

    search = request.args.get('search', '')
    questions = QuestionModel.query.filter(
        (QuestionModel.title.ilike(f'%{search}%'))
    )
    return render_template('movieTalk.html', questions=questions)


@app.route('/reply', methods=["GET", "POST"])
def reply():
    if request.method == 'POST':
        data = request.form.to_dict()
        reply_db = ReplyModel(content=data.get('content'), user_id=g.user.id, question_id=data.get('question_id'))
        db1.session.add(reply_db)
        db1.session.commit()

    search = request.args.get('search', '')
    questions = QuestionModel.query.filter(
        (QuestionModel.title.ilike(f'%{search}%'))
    )
    return render_template('movieTalk.html', questions=questions)


@app.before_request
def my_before_request():
    user_id = session.get("user_id")
    if user_id:
        user = UserModel.query.get(user_id)
        setattr(g, "user", user)
    else:
        setattr(g, "user", None)


@app.context_processor
def my_context_processor():
    return {"user": g.user}

@app.route('/mn')
def mn():
    return render_template("movie-news.html")

@app.route('/movie1')
def movie1():
    return render_template("movie1.html")
@app.route('/movie2')
def movie2():
    return render_template("movie2.html")
@app.route('/movie3')
def movie3():
    return render_template("movie3.html")
@app.route('/movie4')
def movie4():
    return render_template("movie4.html")

@app.route('/mc')
def mc():
    return render_template("movie-column.html")

if __name__ == '__main__':
    app.run(debug=True)

blueprints/auth.py
from flask import Blueprint, render_template, request, redirect, url_for, session
from exts import db
from .forms import RegisterForms, LoginForm
from models import UserModel

bp = Blueprint("auth", __name__, url_prefix="/auth")


@bp.route("/login", methods=['GET', 'POST'])
def login():
    if request.method == 'GET':
        return render_template("login.html")
    else:
        form = LoginForm(request.form)
        if form.validate():
            username = form.username.data
            password = form.password.data
            user = UserModel.query.filter_by(username=username).first()
            if not user:
                print("Username not found")
                return redirect(url_for("auth.login"))
            if user.password == password:
                session['user_id'] = user.id
                return redirect(url_for("index"))
        else:
            print(form.errors)
            return redirect(url_for("auth.login"))


@bp.route("/register", methods=['GET', 'POST'])
def register():
    if request.method == 'GET':
        return render_template("register.html")
    else:
        form = RegisterForms(request.form)
        if form.validate():
            email = form.email.data
            username = form.username.data
            password = form.password.data
            user = UserModel(email=email, username=username, password=password)
            db.session.add(user)
            db.session.commit()
            return redirect(url_for("auth.login"))
        else:
            return render_template("register.html", error=form.errors)


@bp.route("/logout")
def logout():
    session.clear()
    return redirect("/")

blueprints/qa.py
from flask import Blueprint, render_template, request, g, redirect, url_for
from .forms import QuestionForm
from models import QuestionModel, ReplyModel
from exts import db
from decorators import login_require

bp = Blueprint("qa", __name__, url_prefix="/qa")


@bp.route("/mt")
def index():
    questions = QuestionModel.query.order_by(QuestionModel.create_time.desc()).all()
    return render_template("movieTalk.html", questions=questions)


@bp.route("/post", methods=['GET', 'POST'])
@login_require
def post():
    if request.method == 'GET':
        return render_template("post.html")
    else:
        form = QuestionForm(request.form)
        if form.validate():
            title = form.title.data
            content = form.content.data
            question = QuestionModel(title=title, content=content, author=g.user)
            db.session.add(question)
            db.session.commit()
            return redirect("/")
        else:
            print(form.errors)
            return redirect(url_for("qa/post"))


@bp.route("/dt/<qa_id>")
def qa_detail(qa_id):
    question = QuestionModel.query.get(qa_id)
    replies = ReplyModel.query.filter(
        (ReplyModel.question_id == question.id)
    ).all()
    print(question, replies)
    return render_template("detail.html", question=question, replies=replies)

templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="description" content="group project for CITS5505">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
  <title>{% block title %} {% endblock%}</title>
  <link rel="stylesheet" type="text/css" href="{{url_for('static', filename="css/index-styles.css" )}}">
  <script src="https://kit.fontawesome.com/966d149ae8.js" crossorigin="anonymous"></script>
  {% block head %} {% endblock%}
</head>

<body>
  <nav id="container">
    <div id="logo" class="col-md-8">
      <a href="{{ url_for('index')}}">
        <img src="{{ url_for('static', filename='jpg/logo.png') }}" alt="ForumLogo" id="ForumLogo">
      </a>
      
      <p id="headP"></p>
    </div>
    <div id="login" class="col-md-4">
      <ul>
        {% if user %}
        <li><span class="logLink">{{ user.username}}</span></li>
        <li><a class="logLink" href="{{ url_for('auth.logout')}}">Sign Out</a></li>
        {% else %}
        <li><a class="logLink" href="{{ url_for('auth.login')}}">Log In</a></li>
        <li><a class="logLink" href="{{ url_for('auth.register')}}">Register</a></li>
        {% endif %}
        <li><a class="logLink" href="{{ url_for('qa.post')}}">Post</a></li>
      </ul>
    </div>
  </nav>
  {% block body %}
  {% endblock %}
  <footer>
    <div id="copyright">
      <p>
        Coypright © CITS5505 Group Project 2024
      </p>
    </div>
  </footer>
  <script src="{{ url_for('static', filename='js/index-script.js') }}"></script>
</body>
</html>

templates/detail.html
{% extends "base.html"%}

{% block head %}
<link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/dt-styles.css') }}">
{% endblock %}

{% block title%}
{{ question.title }}
{% endblock %}

{% block body %}
<div class="homeBody">
  <div id="nav">
    <ul>
        <li><a class="navLink" href="{{ url_for('mc') }}">FILM COLUMN</a></li>
        <li><a class="navLink" href="{{ url_for('mn') }}">MOVIE NEWSLETTER</a></li>
        <li><a class="navLink" href="{{ url_for('movie_talk') }}" id="selfPage">MOVIE TALK</a></li>
    </ul>
  </div>
  <div class="content">
    <div>
      <div></div>
      <div>
        <h3 class="page-title">{{ question.title }}</h3>
        <p class="question-info">
          <span>Author: {{ question.author.username }}</span>
          <span> Date: {{ question.creat_time }}</span>
        </p>
        <hr>
        <p class="question-content"> {{ question.content }}</p>
        <hr>
        <h4> Comment</h4>
        <div class="post">
          {% for reply in replies %}
          <li>
            <div class="side-post">
              <img class="avator" src="{{ url_for('static', filename='jpg/avatar.jpeg')}}" alt="">
            </div>
            <div class="question-main">
              <div>{{ reply.content }}</div>
              <div class="question-info">
                <span class="question-author">{{ reply.user.username }}</span>
                <span class="question-time">{{ reply.create_time }}</span>
              </div>
            </div>
          </li>
          {% endfor %}
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

templates/index.html
{% extends "base.html"%}

{% block title%}
MovieFun Forum
{% endblock %}

{% block body %}
<div class="homeBody">
  <div id="nav">
    <ul>
        <li><a class="navLink" href="{{ url_for('mc') }}">FILM COLUMN</a></li>
        <li><a class="navLink" href="{{ url_for('mn') }}">MOVIE NEWSLETTER</a></li>
        <li><a class="navLink" href="{{ url_for('movie_talk') }}">MOVIE TALK</a></li>
    </ul>
  </div>

  <div class="scrollTv middle">
    <h3 id="intro">Trending Now:</h3>
    <div class="screen">
      <input type="radio" name="r" id="r1" checked>
      <input type="radio" name="r" id="r2">
      <input type="radio" name="r" id="r3">
      <input type="radio" name="r" id="r4">
      <input type="radio" name="r" id="r5">
      <div class="slide s1">
        <img src="{{ url_for('static', filename='jpg/pic1.jpg')}}" alt="pic1">
      </div>
      <div class=" slide">
        <img src="{{ url_for('static', filename='jpg/pic2.jpg')}}" alt="pic2">
      </div>
      <div class="slide">
        <img src="{{ url_for('static', filename='jpg/pic3.jpg')}}" alt="pic3">
      </div>
      <div class="slide">
        <img src="{{ url_for('static', filename='jpg/pic4.jpg')}}" alt="pic4">
      </div>
      <div class="slide">
        <img src="{{ url_for('static', filename='jpg/pic5.jpg')}}" alt="pic5">
      </div>
    </div>
    <div id="picNav">
      <label for="r1" class="bar"></label>
      <label for="r2" class="bar"></label>
      <label for="r3" class="bar"></label>
      <label for="r4" class="bar"></label>
      <label for="r5" class="bar"></label>
    </div>
  </div>

</div>
{% endblock %}

templates/login.html
{% extends "base.html"%}

{% block head %}
<link rel="stylesheet" type="text/css" href="{{url_for('static', filename="css/login-styles.css" )}}">
{% endblock %}

{% block title%}
MovieFun-Login
{% endblock %}

{% block body %}
<div id="login" class="homeBody">
    <h2>Login</h2>
    <form method="POST" id="userinfo">
        <div class="form-group">
            <label for="username">Username:</label>
            <input type="username" id="username" name="username" required>
        </div>
        <div class="form-group">
            <label for="password">Password:</label>
            <input type="password" id="password" name="password" required>
        </div>
        <button type="submit">Login Now</button>
    </form>
</div>
{% endblock %}

templates/movie-column.html
{% extends "base.html"%}

{% block head %}
<link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/filmcolumn.css') }}">
{% endblock %}

{% block title%}
MovieFun Column
{% endblock %}

{% block body %}

<body class="background container">
    <div id="nav">
        <ul>
            <li><a class="navLink" href="{{ url_for('mc') }}" id="selfPage">FILM COLUMN</a></li>
            <li><a class="navLink" href="{{ url_for('mn') }}">MOVIE NEWSLETTER</a></li>
            <li><a class="navLink" href="{{ url_for('movie_talk') }}">MOVIE TALK</a></li>
        </ul>
    </div>
    <div class="film-container">
        <div class="film">
            <img src="{{ url_for('static', filename='jpg/p511118051.jpg') }}" alt="Action Movie 1 Poster" onclick="showReview('action1')">
            <div class="review" id="action1-review">
                <h3>Leon: The Professional</h3>
                <p>Lyon (played by Jean Reno) is a lonely professional killer who is hired by others. One day, the little neighbor girl Matilda (Natalie Portman) knocked on his door and asked to stay with him to avoid the danger of murder. It turns out that the owner of the neighbor's house was an informant of the police anti-narcotics team. He was punished by the police (Gary Oldman) who killed his entire family just because he embezzled a small package of drugs. Matilda was rescued by Lyon, survived, and stayed with Lyon. Lyon taught the little girl how to use a gun, and she taught Lyon French. The relationship between the two became increasingly close and they got along harmoniously.</p>
                <div class="comment-input">
                    <input type="text" id="commentInput" placeholder="Leave a comment">
                    <button onclick="submitComment(1)" class="btn">Submit Comment</button>
                    <button onclick="likeReview(1)" class="btn">Like</button>
                </div>
            </div>
        </div>
        <div class="film">
            <img src="{{ url_for('static', filename='jpg/am2.jpg') }}" alt="Action Movie 2 Poster" onclick="showReview('action2')">
            <div class="review" id="action2-review">
                <h3>Batman: The Dark Knight / TDK</h3>
                <p>"Batman" has come out of the shadow of witnessing his parents being killed. After growing up, he is no longer the rebellious and lonely hero. With the help of Police Officer Jim Gordon and Prosecutor Harvey Dent, "Batman" continues to run around the world without any worries, fighting an endless battle against the growing criminal threats, and where he is Gotham City is also the place where the progress is most obvious. The crime rate continues to decline at an alarming rate. After all, the opponent is the "Batman" who can go to heaven and earth. Who would dare to make mistakes without borrowing two courages? However, in a city like Gotham where technology and filth coexist, peace cannot be maintained for long. As expected, a new round of chaos soon swept the entire city. People were once again enveloped in panic and claimed to be willing. The person responsible for all this is naturally the source and ruler of all chaos - the "Joker".
                </p>
                <div class="comment-input">
                    <input type="text" id="commentInput" placeholder="Leave a comment">
                    <button onclick="submitComment(1)" class="btn">Submit Comment</button>
                    <button onclick="likeReview(1)" class="btn">Like</button>
                </div>
            </div>
        </div>
        

        <div class="film">
            <img src="{{ url_for('static', filename='jpg/comedy_movie1_poster.jpg') }}" alt="Comedy Movie 1 Poster" onclick="showReview('comedy1')">
            <div class="review" id="comedy1-review">
                <h3>Titanic </h3>
                <p>On April 10, 1912, the luxury liner Titanic, known as the "miracle in the history of world industry", began her maiden voyage from Southampton, England to New York, the United States. Rich girl Rose (Kate Winslet) boarded the first-class cabin with her mother and fiancé Carl; on the other side, bohemian young painter Jack (Leonardo DiCaprio) was also gambling at the pier Won a lower class ticket.
                    Rose was tired of the hypocritical life in the upper class and was unwilling to marry Carl. She planned to commit suicide by throwing herself into the sea, but was rescued by Jack. Soon, the beautiful and lively Rose fell in love with the handsome and cheerful Jack. Jack took Rose to a dance in the lower cabin and took her portrait, and their relationship gradually heated up.
                    April 14, 1912, Sunday night, a calm night. The Titanic hits an iceberg, the "unsinkable" Titanic faces the fate of sinking, and the budding love between Rose and Jack will also experience the test of life and death.</p>
                <div class="comment-input">
                    <input type="text" id="commentInput" placeholder="Leave a comment">
                    <button onclick="submitComment(1)" class="btn">Submit Comment</button>
                    <button onclick="likeReview(1)" class="btn">Like</button>
                </div>
            </div>
        </div>
        <div class="film">
            <img src="{{ url_for('static', filename='jpg/comedy_movie2_poster.jpg') }}" alt="Comedy Movie 2 Poster" onclick="showReview('comedy2')">
            <div class="review" id="comedy2-review">
                <h3>Farewell My Concubine</h3>
                <p>Duan Xiaolou (Zhang Fengyi) and Cheng Dieyi (Leslie Cheung) are a pair of brothers who grew up together. One plays a male role and the other plays a female role. They have always worked together flawlessly, especially in "Farewell My Concubine". Famous in the capital, the two agreed to co-star in "Farewell My Concubine" for the rest of their lives. However, the two have fundamentally different understandings of the relationship between drama and life. Duan Xiaolou understands that drama is not life, while Cheng Dieyi is indifferent between drama and drama.
                    Duan Xiaolou married the famous prostitute Juxian (Gong Li) when he thought it was time to get married and start a business. Cheng Dieyi believed that Juxian was a shameful third party, making Duan Xiaolou a traitor. The love-hate war born out of "Farewell My Concubine" began to escalate with the changes of the times, and eventually led to tragedy.</p>
                <div class="comment-input">
                    <input type="text" id="commentInput" placeholder="Leave a comment">
                    <button onclick="submitComment(1)" class="btn">Submit Comment</button>
                    <button onclick="likeReview(1)" class="btn">Like</button>
                </div>
            </div>
        </div>

        <div class="film">
            <img src="{{ url_for('static', filename='jpg/drama_movie1_poster1.jpg') }}" alt="Drama Movie 1 Poster" onclick="showReview('drama1')">
            <div class="review" id="drama1-review">
                <h3>The Intouchables</h3>
                <p>Because of a skydiving accident, the white rich Philippe (François Cluzet) was paralyzed in bed and wanted to hire a full-time escort. Due to the high salary, there were many applicants, all of whom were eloquent, but they could not move his heart. It wasn't until the appearance of black Driss (Omar Sy) that he made a decision. Driss had just come out of prison and was burdened with family burdens. He just wanted to find a dismissal letter to apply for relief, and he was obviously more interested in the female assistant than this job. But Philip still fell in love with this young man at first sight. So Desis began a one-month trial period. Although the comfortable environment of the mansion made him feel vain, he still faced many challenges: not only did he have to rehabilitate Philip, but he also had to bathe, enema, open letters, wear stockings, etc. At first, the two people's ways of thinking and values were very different, but as their understanding deepened, they became friends...</p>
                <div class="comment-input">
                    <input type="text" id="commentInput" placeholder="Leave a comment">
                    <button onclick="submitComment(1)" class="btn">Submit Comment</button>
                    <button onclick="likeReview(1)" class="btn">Like</button>
                </div>
            </div>
        </div>
        <div class="film">
            <img src="{{ url_for('static', filename='jpg/drama_movie2_poster.jpg') }}" alt="Drama Movie 2 Poster" onclick="showReview('drama2')">
            <div class="review" id="drama2-review">
                <h3>Modern Times </h3>
                <p>In the 1920s, the United States was in a period of economic depression. Unemployment remained high. Workers were squeezed and became a screw in the production of large machines. Charlie (played by Charles Chaplin) is a low-level citizen. He works day and night in a factory with rumbling machines to earn a meager income. Repeated and heavy work made him breathless. He used people's noses as screws to twist them and got them entangled in the belts of the assembly line machine, which made people laugh.
                    Although Charlie is poor, he is very kind. He rescued a homeless girl on the road and lived with her in a shabby but warm home. Every time Charlie, who was penniless, would deliberately commit a crime in order to find food in order to enter prison. The situation improved for a while, and the homeless girl became a popular singing and dancing star. However, the good times were too short-lived.</p>
                <div class="comment-input">
                    <input type="text" id="commentInput" placeholder="Leave a comment">
                    <button onclick="submitComment(1)" class="btn">Submit Comment</button>
                    <button onclick="likeReview(1)" class="btn">Like</button>
                </div>
            </div>
        </div>
        
    </div>

</body>

{% endblock %}

templates/movie-news.html
{% extends "base.html"%}

{% block head %}
<link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/page2-styles.css') }}">
{% endblock %}

{% block title%}
MovieFun Newsletter
{% endblock %}

{% block body %}
    <div class="homeBody2">
        <div id="nav">
            <ul>
                <li><a class="navLink" href="{{ url_for('mc') }}">FILM COLUMN</a></li>
                <li><a class="navLink" href="{{ url_for('mn') }}" id="selfPage">MOVIE NEWSLETTER</a></li>
                <li><a class="navLink" href="{{ url_for('movie_talk') }}">MOVIE TALK</a></li>
            </ul>
        </div>
        <div>
            <h2 style="color: aliceblue;">Latest movie releases</h2>
        </div>
        <div class="movie-grid">
            <div class="movie-item">
                <a href="{{ url_for('movie1') }}" style="text-decoration: none; color: inherit;">
                    <img src="{{ url_for('static', filename='jpg/movie1.jpg')}}" alt="Movie 1" width="300" height="450">
                </a>
                <a href="{{ url_for('movie1') }}" style="text-decoration: none; color: inherit;">
                    <span style="font-size: 24px; font-weight: bold;">The Ministry of Ungentlemanly Warfare</span>
                </a>
            </div>
            <div class="movie-item">
                <a href="{{ url_for('movie2') }}" style="text-decoration: none; color: inherit;">
                    <img src="{{ url_for('static', filename='jpg/movie2.jpg')}}" alt="Movie 2" width="300" height="450">
                </a>
                <a href="{{ url_for('movie2') }}" style="text-decoration: none; color: inherit;">
                    <span style="font-size: 24px; font-weight: bold;">Ghostbusters: Frozen Empire</span>
                </a>
            </div>
            <div class="movie-item">
                <a href="{{ url_for('movie3') }}" style="text-decoration: none; color: inherit;">
                    <img src="{{ url_for('static', filename='jpg/movie3.jpg')}}" alt="Movie 3" width="300" height="450">
                </a>
                <a href="{{ url_for('movie3') }}" style="text-decoration: none; color: inherit;">
                    <span style="font-size: 24px; font-weight: bold;">Cabrini</span>
                </a>
            </div>
            <div class="movie-item">
                <a href="{{ url_for('movie4') }}" style="text-decoration: none; color: inherit;">
                    <img src="{{ url_for('static', filename='jpg/movie4.jpg')}}" alt="Movie 4" width="300" height="450">
                </a>
                <a href="{{ url_for('movie4') }}" style="text-decoration: none; color: inherit;">
                    <span style="font-size: 24px; font-weight: bold;">Kung Fu Panda 4</span>
                </a>
            </div>
        </div>
    </div>


{% endblock %}




<body class="NewsSection" id="NewsSection">
    






    </div>

templates/movieTalk.html
{% extends "base.html"%}

{% block head %}
<link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/talk-styles.css') }}">
{% endblock %}

{% block title%}
MovieFun-MovieTalk
{% endblock %}

{% block body %}
<div class="homeBody">
  <div id="nav">
    <ul>
        <li><a class="navLink" href="{{ url_for('mc') }}">FILM COLUMN</a></li>
        <li><a class="navLink" href="{{ url_for('mn') }}">MOVIE NEWSLETTER</a></li>
        <li><a class="navLink" href="{{ url_for('movie_talk') }}" id="selfPage">MOVIE TALK</a></li>
    </ul>
  </div>
  <form class="content" action="/movieTalk" method="post">
    <div class="mb-3">
      <label for="title" class="form-label">Title</label>
      <input type="text" class="form-control" id="title" name="title" aria-describedby="title">
    </div>
    <div class="mb-3">
      <label for="content" class="form-label">Content</label>
      <input type="text" class="form-control" id="content1" name="content">
    </div>
    <button type="submit" class="btn btn-secondary">Submit</button>
  </form>
  <form class="row content" method="get" action="/movieTalk">
    <div class="col-auto">
      <label for="search" class="visually-hidden">Title</label>
      <input type="text" class="form-control" id="search" name="search" placeholder="" style="width: 400px">
    </div>
    <div class="col-auto">
      <button type="submit" class="btn btn-secondary mb-3">Search</button>
    </div>
  </form>
  <div class="content">
    <ul class="post">
      {% for question in questions %}
      <li>
        <div class="side-post">
          <img class="avator" src="{{ url_for('static', filename='jpg/avatar.jpeg')}}" alt="">
        </div>
        <div class="question-main">
          <div><a href="{{ url_for('qa.qa_detail', qa_id=question.id)}}">{{ question.title }}</a></div>
          <div>{{ question.content }}</div>
          <div class="question-info">
            <span class="question-author">{{ question.author.username }}</span>
            <span class="question-time">{{ question.create_time }}</span>
          </div>
          <div style="display:flex;align-items: center">
            <form class="row" method="post" action="/reply" style="margin-left: auto">
              <div class="col-auto">
                <input type="text" class="form-control" id="question_id" name="question_id" value="{{question.id}}" style="display: none">
                <input type="text" class="form-control" id="content" name="content" placeholder=""
                  style="width: 600px">
              </div>
              <div class="col-auto">
                <button type="submit" class="btn btn-secondary mb-3">Reply</button>
              </div>
            </form>
          </div>
        </div>
      </li>
      {% endfor %}
    </ul>
  </div>
</div>
{% endblock %}

templates/post.html
{% extends "base.html" %}

{% block head %}
<link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/post-styles.css') }}">
{% endblock %}

{% block title%}
MovieFun-MovieTalk
{% endblock %}

{% block body %}
<div class="homeBody">
  <div id="nav">
    <ul>
        <li><a class="navLink" href="{{ url_for('mc') }}">FILM COLUMN</a></li>
        <li><a class="navLink" href="{{ url_for('mn') }}">MOVIE NEWSLETTER</a></li>
        <li><a class="navLink" href="{{ url_for('movie_talk') }}" id="selfPage">MOVIE TALK</a></li>
    </ul>
  </div>
  <div class="content">
    <div>
      <div></div>
      <div>
        <h1>Post Your Idea</h1>
        <form action="#" method="POST">
          <div>
            <input type="text" name="title" class="form-control" placeholder="Please type title">
          </div>
          <div>
            <textarea name="content" class="form-control" placeholder="Please type content"></textarea>
          </div>
          <div class="form-group">
            <button class="btn">Post Now</button>
          </div>
        </form>
      </div>
    </div>
  </div>
</div>
{% endblock %}